default_platform(:android)

platform :android do
  desc "Lane for Android firebase app distribution"
  lane :firebase_distribution do
    # sh "flutter clean"
    # sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
  
    # Upload the APK to Firebase App Distribution
    firebase_app_distribution(
      app: "1:902539622121:android:d40e112102a9d09d23a278",
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"], 
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "tarekahmedbelal@gmail.com",
      release_notes: "second fastlane firebase distribution"
    )
  end 
end
