name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - development

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        cache: true


    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4.0"
        bundler-cache: true
        working-directory: android

    - name: Install dependencies
      run: |
        gem install bundler --user-install
        bundle config set --local path 'vendor/bundle'
        bundle install --verbose
      working-directory: android
   

    - name: Make Gradle Executable
      run: chmod +x android/gradlew
      working-directory: android
     
    - name: Build and Distribute App for Firebase
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: |
       bundle exec fastlane android firebase_distribution
      working-directory: android